language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - TESTBENCH_VERSION=3.1.*
    - TESTBENCH_VERSION=3.2.*
    - TESTBENCH_VERSION=3.3.*
    allow_failures:
      - TESTBENCH_VERSION=3.4.*
  global:
    - COMPOSER_DISCARD_CHANGES=true
    - COMPOSER_NO_INTERACTION=1
    - COMPOSER_DISABLE_XDEBUG_WARN=1

before_install:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer self-update && composer -V
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update -v

install:
  - travis_retry composer update --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls

notifications:
  email:
    on_success: never
    on_failure: change
