language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

addons:
  code_climate:
    repo_token: e9d8026b4a1ca0f1c3577c3772bbe9d8d337f0cb2ee50642d2047efa8a148327

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ] || [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/test-reporter; fi

notifications:
  email:
    on_success: never
    on_failure: change
